version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=WorkoutsDB
    volumes:
      - ./postgres_data:/var/lib/postgresql/data




  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    restart: always
    ports:
      - '5555:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password

  app:
    image: nicknav98/gymplanner:latest
    ports:
      - '5050:5050'

volumes:
  postgres_data:
    driver: local
