version: '3'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - '5446:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=WorkoutsDB


  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    restart: always
    ports:
      - '5555:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password










